object Versions {
    const val appCompatVersion = "28.0.0"
    const val recyclerViewVersion = "1.2.1"
    const val androidCoreVersion: String = "1.7.0"
    const val constraintLayoutVersion: String = "2.0.0-beta4"
    const val composeVersion: String = "1.1.1"
    const val composeRuntimeVersion: String = "1.2.0-alpha08"
    const val materialVersion: String = "1.1.0"
    const val activityComposeVersion = "1.4.0"
    const val navigationComposeVersion = "2.4.2"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val lifecycleVersion = "2.4.1"
    const val retrofitVersion = "2.9.0"
    const val roomVersion = "2.4.2"
    const val hiltVersion = "2.42"
    const val gsonVersion = "2.8.6"
    const val hiltTestVersion = "2.41"
    const val junitVersion = "4.13.2"
    const val espressoVersion = "3.4.0"
    const val jUnitVersion = "1.1.3"
    const val kotlinCompilerExtensionVersion = "1.1.1"
    const val coroutinesTestVersion = "1.6.1"
    const val archTestingVersion = "2.1.0"
    const val mockitoKotlinVersion = "4.0.0"
    const val mockitoAndroidVersion = "4.3.1"
    const val okHttpVersion = "4.9.3"
    const val picassoVersion = "2.5.2"
}
